---
# This playbook will install mysql and create db user and give permission
- name: Install Mysql packages
  yum:
    name: [
      'mysql-community-server', 
      'MySQL-python', 
      'libselinux-python', 
      'libsemanage-python'
    ]
    state: installed
    update_cache: yes

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes
  when: sestatus.rc != 0

- name: Create MySQL configuration file
  template:
    src: my.cnf.j2 
    dest: /etc/my.cnf
  notify:
    - restart mysql

- name: Start mysql service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Stop mysql service
  service:
    name: mysqld
    state: stopped

- name: Start mysql insecure
  shell: mysqld --skip-grant-tables &
  
- name: Change mysql root password
  shell:  mysql -uroot mysql -e "UPDATE user SET Password=PASSWORD('my_password') where USER='root';"

- name: Kill mysqld process
  shell: killall -9 mysqld

- name: Start mysql service
  service:
    name: mysqld
    state: started
    
