---
# This playbook will install mysql and create db user and give permission
- name: Install Mysql packages
  yum:
    name: [
      'mysql-server', 
      'MySQL-python', 
      'libselinux-python', 
      'libsemanage-python'
    ]
    state: installed
    update_cache: yes

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes
  when: sestatus.rc != 0

- name: Create MySQL configuration file
  template:
    src: my.cnf.j2 
    dest: /etc/my.cnf
  notify:
    - restart mysql

- name: Start mysql service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Create Application Database
  mysql_db:
    name: "{{ dbname }}"
    state: present

- name: Create Application DB user
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: "{{ dbname }}.*:ALL"
    host: localhost
    state: present

- name: Import database project
  mysql_db:
    state: import
    name: "{{ dbname }}"
    target: /var/www/html/simple_lamp.sql

- debug:
    msg: "Your setup is now available at http://127.0.0.1:8081"