---
# This playbook will install mysql and create db user and give permission
- name: Install Mysql packages
  yum:
    name: [
      'mysql-community-server', 
      'MySQL-python', 
      'libselinux-python', 
      'libsemanage-python'
    ]
    state: installed
    update_cache: yes

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes
  when: sestatus.rc != 0

- name: Create MySQL configuration file
  template:
    src: my.cnf.j2 
    dest: /etc/my.cnf
  notify:
    - restart mysql

- name: Start mysql service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Stop mysql service
  service:
    name: mysqld
    state: stopped

- name: Start mysql insecure
  shell: mysqld --skip-grant-tables &

- name: Change mysql root password
#  shell:  mysql -uroot mysql -e "update user set authentication_string=password('my_password') where user='root';"
  shell: mysql -uroot mysql -e "UPDATE mysql.user SET authentication_string = PASSWORD('my_password'), password_expired = 'N' WHERE User = 'root' AND Host = 'localhost'; FLUSH PRIVILEGES;"

- name: Kill mysqld process
  shell: killall -9 mysqld

- name: Start mysql service
  service:
    name: mysqld
    state: started

- name: Create database for WebAPP
  mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: root
    login_password: "{{ mysql_root_passwd }}"
    login_host: "localhost"
    name: "{{ dbname }}"
    state: present
    
- name: Create Application DB user
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: "root"
    login_host: "localhost"
    login_password: "{{ mysql_root_passwd }}"
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: "{{ dbname }}.*:ALL"
    host: localhost
    state: present

- name: Import database project
  mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: "root"
    login_host: "localhost"
    login_password: "{{ mysql_root_passwd }}"
    state: import
    name: "{{ dbname }}"
    target: /var/www/html/simple_lamp.sql

