---
# These tasks are responsible for copying the latest
# dev/production code from the version control system.
- name: Clone app code to be published
  git:
    repo: "{{ repository }}"
    dest: /var/www/html

